variables:
  WORKSPACE: /w/techradar

stages:
  - update
  - deploy

update_local_repo:
  stage: update
  only:
    - master
  script:
    - ssh-agent bash -c 'ssh-add $WORKSPACE/deploy.key; cd $WORKSPACE/website; git pull'
  tags:
    - dip-shell-runner

deploy:
  stage: deploy
  only:
    - master
  tags:
    - dip-shell-runner
  script:
    - cd $WORKSPACE
    - docker-compose build
    - docker-compose up -d
